### ISSUE TITLE
Object detection test.py throughs an error

### ISSUE THREAD

**Issue by SarfarazHabib** [calmevtime/DCTNet#28]
Hey, thanks for your work again. I was trying your object detection code on coco dataset and was hoping to see the code run for evaluation but when I ran the test.py it gives me this error..

>>> from mmdet.apis import init_dist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sarfaraz/DCTNet/segmentation/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'
>>> import mmdet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sarfaraz/DCTNet/segmentation/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

Can you point out whats going wrong here ?

**Comment by SarfarazHabib** [comment]
I solved this problem, it looks like mmdetection was not built correctly. But i am having new problems now.
After doing some more digging, I found out that the mmdetection has been updated and the latest version and commits have changed alot. And does not allign with the test.py that you wrote. Looks like you used some previous versions, can you please which versions you were using ? or which previous commits can i try ?

**Comment by Nghingtim** [comment]
> I solved this problem, it looks like mmdetection was not built correctly. But i am having new problems now.
> After doing some more digging, I found out that the mmdetection has been updated and the latest version and commits have changed alot. And does not allign with the test.py that you wrote. Looks like you used some previous versions, can you please which versions you were using ? or which previous commits can i try ?

**Comment by Nghingtim** [comment]
I also have this problem after install the latest mmdetection.  It shows:
----------------------------
cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/wqt/Projects/mmdetection/mmdet/ops/dcn/__init__.py)
----------------------------

I have google the error. Most answers suggest that reinstall mmdetection. So it the version problem. 
My question is what is your mmdetection version?  

My env is Linux18.04+Pytorch 1.6.0+ Cuda10.1.
